# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) { transformation: [-1.3333f,0f,0f,0f,0f,1.3333f,0f,0f,0f,0f,-1.3333f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(head) { transformation: [-1.3437f,0f,0f,0f,0f,1.3438f,0f,0f,0f,0f,-1.3437f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(nekutai) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(body) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(right1) { transformation: [-1f,0f,0f,0.3125f,0f,1f,0f,1.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(left1) { transformation: [-1f,0f,0f,-0.375f,0f,1f,0f,1.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(left) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(right) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(cap) { transformation: [-1.4144f,0f,0f,0f,0f,1.4023f,-0.1846f,-0.0469f,0f,-0.1846f,-1.4023f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(line) { transformation: [-1.1523f,0f,0f,0f,0f,1.1523f,0f,0f,0f,0f,-1.1523f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(manto) { transformation: [-1.0208f,0f,0f,0f,0f,1.0208f,0f,0f,0f,0f,-1.0208f,0f,0f,0f,0f,1f], start_interpolation: -1 }