# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) {transformation: [-1.3333f,0f,0f,0f,0f,1.3321f,0.0582f,-0.4687f,0f,0.0582f,-1.3321f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.3437f,0f,0f,0f,0f,1.3438f,0f,-0.4687f,0f,0f,-1.3437f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nekutai) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.4687f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.4687f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-0.9914f,-0.1305f,0f,0.2906f,-0.1305f,0.9914f,0f,0.875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-0.9914f,0.1305f,0f,-0.3656f,0.1305f,0.9914f,0f,0.8594f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-0.9962f,0.0872f,0f,-0.0563f,0f,0f,-1f,0.1406f,-0.0872f,-0.9962f,0f,0.625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-0.9914f,-0.1305f,0f,0.0531f,0f,0f,-1f,0.1406f,0.1305f,-0.9914f,0f,0.6406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cap) {transformation: [-1.4144f,0f,0f,0f,0f,1.4023f,-0.1846f,-0.5156f,0f,-0.1846f,-1.4023f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line) {transformation: [-1.1523f,0f,0f,0f,0f,1.125f,0.2494f,-0.4062f,0f,0.2494f,-1.125f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(manto) {transformation: [-1.0208f,0f,0f,0f,0f,0.9966f,0.2209f,-0.4062f,0f,0.2209f,-0.9966f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}