# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) {transformation: [1.3438f,0f,0f,0f,0f,1.3438f,0f,-0.125f,0f,0f,1.3438f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(wear) {transformation: [1f,0f,0f,0f,0f,1f,0f,-0.125f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [1.0021f,0f,0f,0f,0f,1.0021f,0f,-0.125f,0f,0f,1.0021f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [0.9397f,0.342f,0f,-0.3281f,-0.342f,0.9397f,0f,1.2656f,0f,0f,1f,0.0156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [0.9239f,-0.3827f,0f,0.3594f,0.3827f,0.9239f,0f,1.1406f,0f,0f,1f,0.0156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [0.9726f,-0.2156f,-0.0872f,0.3438f,0.1984f,0.9647f,-0.173f,0f,0.1214f,0.151f,0.9811f,-0.1094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [0.9811f,0.173f,0.0872f,-0.0937f,-0.1561f,0.9725f,-0.173f,-0.0156f,-0.1147f,0.1561f,0.9811f,-0.1406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(skirt) {transformation: [1f,0f,0f,0f,0f,0.9962f,-0.0872f,0.0313f,0f,0.0872f,0.9962f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}