# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) {transformation: [-1.3332f,0f,0.017f,0f,0f,1.3333f,0f,0f,-0.017f,0f,-1.3332f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.3436f,0f,0.0172f,0f,0f,1.3438f,0f,0f,-0.0172f,0f,-1.3436f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nekutai) {transformation: [-0.9999f,0f,0.014f,0f,0f,1f,0f,0f,-0.014f,0f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.9999f,0f,0.014f,0f,0f,1f,0f,0f,-0.014f,0f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-0.9999f,-0.0085f,0.0056f,0.3135f,-0.0084f,1f,0.001f,1.373f,-0.0057f,0.001f,-1f,0.0044f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-1f,0.007f,0.0012f,-0.3736f,0.0071f,0.9997f,0.0227f,1.3741f,-0.0011f,0.0227f,-0.9997f,-0.0052f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-0.999f,0.0436f,0.014f,-0.0146f,0.0436f,0.999f,0f,0f,-0.0139f,0.0006f,-0.9999f,0.0008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-0.999f,-0.0433f,0.0148f,0.0156f,-0.0436f,0.9989f,-0.0195f,-0.002f,-0.0139f,-0.0202f,-0.9997f,0.0042f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cap) {transformation: [-1.4143f,0.0023f,0.0177f,0f,0f,1.4023f,-0.1846f,-0.0469f,-0.0179f,-0.1846f,-1.4022f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line) {transformation: [-1.1522f,0f,0.0161f,0f,0f,1.1523f,0f,0f,-0.0161f,0f,-1.1522f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(manto) {transformation: [-1.0207f,0f,0.0143f,0f,0f,1.0208f,0f,0f,-0.0143f,0f,-1.0207f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}