# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) {transformation: [-1.3097f,0f,0.2497f,0f,0f,1.3333f,0f,0f,-0.2497f,0f,-1.3097f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.32f,0f,0.2516f,0f,0f,1.3438f,0f,0f,-0.2516f,0f,-1.32f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nekutai) {transformation: [-0.9763f,0f,0.2164f,0f,0f,1f,0f,0f,-0.2164f,0f,-0.9763f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.9763f,0f,0.2164f,0f,0f,1f,0f,0f,-0.2164f,0f,-0.9763f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-0.9877f,-0.13f,0.0872f,0.3203f,-0.1305f,0.9914f,0f,1.3438f,-0.0864f,-0.0114f,-0.9962f,0.071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-0.994f,0.0948f,0.0538f,-0.3432f,0.1079f,0.925f,0.3644f,1.3594f,-0.0152f,0.368f,-0.9297f,-0.0761f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-0.9754f,0.0426f,0.2164f,-0.0034f,0.0436f,0.999f,0f,0f,-0.2162f,0.0094f,-0.9763f,0.0153f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-0.9754f,0.0245f,0.2192f,0.0017f,-0.0436f,0.9528f,-0.3004f,-0.0312f,-0.2162f,-0.3026f,-0.9283f,0.0644f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cap) {transformation: [-1.3901f,0.034f,0.2585f,0f,0f,1.4023f,-0.1846f,-0.0469f,-0.2607f,-0.1815f,-1.3783f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line) {transformation: [-1.125f,0f,0.2494f,0f,0f,1.1523f,0f,0f,-0.2494f,0f,-1.125f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(manto) {transformation: [-0.9966f,0f,0.2209f,0f,0f,1.0208f,0f,0f,-0.2209f,0f,-0.9966f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}