# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) {transformation: [-1.3116f,0f,0.2397f,0f,0f,1.3333f,0f,0f,-0.2397f,0f,-1.3116f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.3219f,0f,0.2416f,0f,0f,1.3438f,0f,0f,-0.2416f,0f,-1.3219f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nekutai) {transformation: [-0.993f,0f,0.1182f,0f,0f,1f,0f,0f,-0.1182f,0f,-0.993f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.993f,0f,0.1182f,0f,0f,1f,0f,0f,-0.1182f,0f,-0.993f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-0.9914f,-0.1298f,-0.0181f,0.3266f,-0.1305f,0.9905f,0.0432f,1.3438f,0.0124f,0.0452f,-0.9989f,0.0321f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-0.9958f,0.0914f,-0.0106f,-0.3378f,0.0903f,0.9929f,0.0773f,1.3518f,0.0176f,0.076f,-0.997f,-0.0402f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-0.9849f,0.0433f,0.1675f,0.0012f,0.0436f,0.999f,-0.0022f,0f,-0.1674f,0.0052f,-0.9859f,0.0091f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-0.9798f,-0.0067f,0.1998f,0.0225f,-0.068f,0.9511f,-0.3013f,-0.0246f,-0.188f,-0.3088f,-0.9323f,0.0566f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cap) {transformation: [-1.3897f,0.0343f,0.2607f,0f,0f,1.4023f,-0.1846f,-0.0469f,-0.263f,-0.1814f,-1.3778f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line) {transformation: [-1.1442f,0f,0.1361f,0f,0f,1.1523f,0f,0f,-0.1361f,0f,-1.1442f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(manto) {transformation: [-1.0137f,0f,0.1206f,0f,0f,1.0208f,0f,0f,-0.1206f,0f,-1.0137f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}