# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) {transformation: [-1.3197f,0f,0.1905f,0f,0f,1.3333f,0f,0f,-0.1905f,0f,-1.3197f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.33f,0f,0.192f,0f,0f,1.3438f,0f,0f,-0.192f,0f,-1.33f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nekutai) {transformation: [-0.9998f,0f,0.0187f,0f,0f,1f,0f,0f,-0.0187f,0f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.9998f,0f,0.0187f,0f,0f,1f,0f,0f,-0.0187f,0f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-0.9852f,-0.1195f,-0.1228f,0.3283f,-0.1305f,0.9877f,0.0864f,1.3438f,0.111f,0.1012f,-0.9887f,-0.0073f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-0.9961f,0.0591f,-0.0653f,-0.3376f,0.0719f,0.9739f,-0.2151f,1.3501f,0.0508f,-0.219f,-0.9744f,-0.0063f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-0.992f,0.0436f,0.1181f,0.0044f,0.0434f,0.999f,-0.0043f,0f,-0.1181f,0.0008f,-0.993f,0.0023f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-0.9829f,-0.0381f,0.1804f,0.0416f,-0.0917f,0.9499f,-0.2988f,-0.0179f,-0.16f,-0.3102f,-0.9371f,0.0454f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cap) {transformation: [-1.3972f,0.0287f,0.2176f,0f,0f,1.4023f,-0.1846f,-0.0469f,-0.2195f,-0.1824f,-1.3853f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line) {transformation: [-1.1521f,0f,0.0215f,0f,0f,1.1523f,0f,0f,-0.0215f,0f,-1.1521f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(manto) {transformation: [-1.0207f,0f,0.0191f,0f,0f,1.0208f,0f,0f,-0.0191f,0f,-1.0207f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}