# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) {transformation: [-1.3259f,0f,0.141f,0f,0f,1.3333f,0f,0f,-0.141f,0f,-1.3259f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.3362f,0f,0.1421f,0f,0f,1.3438f,0f,0f,-0.1421f,0f,-1.3362f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nekutai) {transformation: [-0.9967f,0f,-0.0809f,0f,0f,1f,0f,0f,0.0809f,0f,-0.9967f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.9967f,0f,-0.0809f,0f,0f,1f,0f,0f,0.0809f,0f,-0.9967f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-0.9693f,-0.0991f,-0.2252f,0.3254f,-0.1305f,0.983f,0.1294f,1.3438f,0.2086f,0.1548f,-0.9657f,-0.0466f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-0.995f,0.0049f,-0.0994f,-0.3341f,0.053f,0.8715f,-0.4875f,1.3485f,0.0843f,-0.4903f,-0.8675f,0.0271f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-0.9967f,0.0435f,0.0684f,0.0063f,0.0431f,0.999f,-0.0065f,0f,-0.0686f,-0.0035f,-0.9976f,-0.005f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-0.9846f,-0.0691f,0.1605f,0.0585f,-0.1144f,0.9493f,-0.2929f,-0.0112f,-0.1322f,-0.3067f,-0.9426f,0.0311f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cap) {transformation: [-1.4034f,0.023f,0.1744f,0f,0f,1.4023f,-0.1846f,-0.0469f,-0.1759f,-0.1832f,-1.3914f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line) {transformation: [-1.1485f,0f,-0.0933f,0f,0f,1.1523f,0f,0f,0.0933f,0f,-1.1485f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(manto) {transformation: [-1.0175f,0f,-0.0826f,0f,0f,1.0208f,0f,0f,0.0826f,0f,-1.0175f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}