# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) {transformation: [-1.3302f,0f,0.0914f,0f,0f,1.3333f,0f,0f,-0.0914f,0f,-1.3302f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.3406f,0f,0.0921f,0f,0f,1.3438f,0f,0f,-0.0921f,0f,-1.3406f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nekutai) {transformation: [-0.9837f,0f,-0.1798f,0f,0f,1f,0f,0f,0.1798f,0f,-0.9837f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.9837f,0f,-0.1798f,0f,0f,1f,0f,0f,0.1798f,0f,-0.9837f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-0.9437f,-0.0691f,-0.3236f,0.318f,-0.1305f,0.9764f,0.1722f,1.3438f,0.304f,0.2047f,-0.9304f,-0.0853f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-0.9925f,-0.0611f,-0.1062f,-0.3276f,0.0339f,0.6963f,-0.717f,1.347f,0.1178f,-0.7152f,-0.689f,0.0599f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-0.9989f,0.0429f,0.0185f,0.0068f,0.0428f,0.999f,-0.0086f,0f,-0.0189f,-0.0078f,-0.9998f,-0.0126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-0.9852f,-0.099f,0.14f,0.0729f,-0.1357f,0.9493f,-0.2837f,-0.0045f,-0.1048f,-0.2985f,-0.9486f,0.0139f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cap) {transformation: [-1.4082f,0.0172f,0.1309f,0f,0f,1.4023f,-0.1846f,-0.0469f,-0.1321f,-0.1838f,-1.3962f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line) {transformation: [-1.1335f,0f,-0.2072f,0f,0f,1.1523f,0f,0f,0.2072f,0f,-1.1335f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(manto) {transformation: [-1.0042f,0f,-0.1835f,0f,0f,1.0208f,0f,0f,0.1835f,0f,-1.0042f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}