# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) {transformation: [-1.3327f,0f,0.0415f,0f,0f,1.3333f,0f,0f,-0.0415f,0f,-1.3327f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.3431f,0f,0.0419f,0f,0f,1.3438f,0f,0f,-0.0419f,0f,-1.3431f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nekutai) {transformation: [-0.9609f,0f,-0.2768f,0f,0f,1f,0f,0f,0.2768f,0f,-0.9609f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.9609f,0f,-0.2768f,0f,0f,1f,0f,0f,0.2768f,0f,-0.9609f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-0.9087f,-0.0302f,-0.4163f,0.306f,-0.1305f,0.9679f,0.2146f,1.3438f,0.3965f,0.2493f,-0.8835f,-0.123f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-0.9884f,-0.1272f,-0.0832f,-0.3182f,0.0147f,0.4646f,-0.8854f,1.3458f,0.1512f,-0.8763f,-0.4573f,0.0917f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-0.9986f,0.0419f,-0.0314f,0.0058f,0.0423f,0.999f,-0.0108f,0f,0.0309f,-0.0121f,-0.9994f,-0.0202f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-0.9848f,-0.1272f,0.1185f,0.0843f,-0.1553f,0.9498f,-0.2714f,0.0022f,-0.0781f,-0.2857f,-0.9551f,-0.0057f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cap) {transformation: [-1.4116f,0.0115f,0.0874f,0f,0f,1.4023f,-0.1846f,-0.0469f,-0.0881f,-0.1843f,-1.3996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line) {transformation: [-1.1072f,0f,-0.319f,0f,0f,1.1523f,0f,0f,0.319f,0f,-1.1072f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(manto) {transformation: [-0.9809f,0f,-0.2826f,0f,0f,1.0208f,0f,0f,0.2826f,0f,-0.9809f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}