# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) {transformation: [-1.3333f,0f,-0.0083f,0f,0f,1.3333f,0f,0f,0.0083f,0f,-1.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.3437f,0f,-0.0084f,0f,0f,1.3438f,0f,0f,0.0084f,0f,-1.3437f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nekutai) {transformation: [-0.9286f,0f,-0.3711f,0f,0f,1f,0f,0f,0.3711f,0f,-0.9286f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.9286f,0f,-0.3711f,0f,0f,1f,0f,0f,0.3711f,0f,-0.9286f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-0.8647f,0.0166f,-0.502f,0.2898f,-0.1305f,0.9577f,0.2566f,1.3438f,0.485f,0.2874f,-0.8259f,-0.1591f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-0.9828f,-0.1816f,-0.0323f,-0.3059f,-0.0042f,0.1969f,-0.9804f,1.3446f,0.1844f,-0.9634f,-0.1943f,0.1223f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-0.9959f,0.0405f,-0.0812f,0.0033f,0.0417f,0.999f,-0.0129f,0f,0.0806f,-0.0162f,-0.9966f,-0.0278f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-0.9836f,-0.1529f,0.0958f,0.0924f,-0.1728f,0.951f,-0.2562f,0.0089f,-0.052f,-0.2686f,-0.9619f,-0.0273f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cap) {transformation: [-1.4137f,0.0058f,0.0437f,0f,0f,1.4023f,-0.1846f,-0.0469f,-0.0441f,-0.1845f,-1.4016f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line) {transformation: [-1.07f,0f,-0.4276f,0f,0f,1.1523f,0f,0f,0.4276f,0f,-1.07f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(manto) {transformation: [-0.9479f,0f,-0.3789f,0f,0f,1.0208f,0f,0f,0.3789f,0f,-0.9479f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}