# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) {transformation: [-1.3328f,0f,0.0384f,0f,0f,1.3333f,0f,0f,-0.0384f,0f,-1.3328f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.3432f,0f,0.0387f,0f,0f,1.3438f,0f,0f,-0.0387f,0f,-1.3432f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nekutai) {transformation: [-0.9995f,0f,0.0332f,0f,0f,1f,0f,0f,-0.0332f,0f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.9995f,0f,0.0332f,0f,0f,1f,0f,0f,-0.0332f,0f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-0.9997f,-0.0201f,0.0134f,0.3147f,-0.0201f,0.9998f,0.0022f,1.3703f,-0.0134f,0.0019f,-0.9999f,0.0104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-0.9999f,0.0166f,0.0034f,-0.3718f,0.0168f,0.9984f,0.0541f,1.373f,-0.0025f,0.0542f,-0.9985f,-0.0123f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-0.9985f,0.0436f,0.0332f,-0.0133f,0.0436f,0.999f,0f,0f,-0.0331f,0.0014f,-0.9995f,0.0019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-0.9985f,-0.042f,0.0351f,0.0153f,-0.0436f,0.998f,-0.0464f,-0.0048f,-0.0331f,-0.0478f,-0.9983f,0.01f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cap) {transformation: [-1.4138f,0.0052f,0.0398f,0f,0f,1.4023f,-0.1846f,-0.0469f,-0.0401f,-0.1845f,-1.4017f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line) {transformation: [-1.1516f,0f,0.0382f,0f,0f,1.1523f,0f,0f,-0.0382f,0f,-1.1516f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(manto) {transformation: [-1.0203f,0f,0.0338f,0f,0f,1.0208f,0f,0f,-0.0338f,0f,-1.0203f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}