# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) {transformation: [-1.3321f,0f,-0.0582f,0f,0f,1.3333f,0f,0f,0.0582f,0f,-1.3321f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.3425f,0f,-0.0586f,0f,0f,1.3438f,0f,0f,0.0586f,0f,-1.3425f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nekutai) {transformation: [-0.887f,0f,-0.4617f,0f,0f,1f,0f,0f,0.4617f,0f,-0.887f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.887f,0f,-0.4617f,0f,0f,1f,0f,0f,0.4617f,0f,-0.887f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-0.8121f,0.0705f,-0.5792f,0.2694f,-0.1305f,0.9456f,0.2981f,1.3438f,0.5687f,0.3177f,-0.7587f,-0.1931f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-0.9758f,-0.2147f,0.0402f,-0.2911f,-0.0226f,-0.0842f,-0.9962f,1.3438f,0.2173f,-0.973f,0.0773f,0.1515f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-0.9907f,0.0387f,-0.1308f,-0.0006f,0.041f,0.999f,-0.0149f,0f,0.1301f,-0.0201f,-0.9913f,-0.0349f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-0.9818f,-0.1758f,0.0718f,0.097f,-0.188f,0.9528f,-0.2384f,0.0156f,-0.0265f,-0.2475f,-0.9685f,-0.0505f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cap) {transformation: [-1.4144f,0f,0f,0f,0f,1.4023f,-0.1846f,-0.0469f,0f,-0.1846f,-1.4023f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line) {transformation: [-1.0221f,0f,-0.5321f,0f,0f,1.1523f,0f,0f,0.5321f,0f,-1.0221f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(manto) {transformation: [-0.9055f,0f,-0.4714f,0f,0f,1.0208f,0f,0f,0.4714f,0f,-0.9055f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}