# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) {transformation: [-1.3318f,0f,0.0631f,0f,0f,1.3333f,0f,0f,-0.0631f,0f,-1.3318f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.3422f,0f,0.0636f,0f,0f,1.3438f,0f,0f,-0.0636f,0f,-1.3422f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nekutai) {transformation: [-0.9984f,0f,0.0563f,0f,0f,1f,0f,0f,-0.0563f,0f,-0.9984f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.9984f,0f,0.0563f,0f,0f,1f,0f,0f,-0.0563f,0f,-0.9984f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-0.9992f,-0.0341f,0.0227f,0.316f,-0.034f,0.9994f,0.0033f,1.3669f,-0.0228f,0.0025f,-0.9997f,0.0178f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-0.9996f,0.0279f,0.0069f,-0.3695f,0.0284f,0.9953f,0.0924f,1.3717f,-0.0042f,0.0926f,-0.9957f,-0.0208f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-0.9975f,0.0436f,0.0563f,-0.0118f,0.0436f,0.999f,0f,0f,-0.0562f,0.0025f,-0.9984f,0.0034f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-0.9975f,-0.039f,0.0595f,0.0147f,-0.0436f,0.9959f,-0.0786f,-0.0081f,-0.0562f,-0.081f,-0.9951f,0.017f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cap) {transformation: [-1.4129f,0.0086f,0.0651f,0f,0f,1.4023f,-0.1846f,-0.0469f,-0.0657f,-0.1844f,-1.4008f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line) {transformation: [-1.1504f,0f,0.0648f,0f,0f,1.1523f,0f,0f,-0.0648f,0f,-1.1504f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(manto) {transformation: [-1.0192f,0f,0.0574f,0f,0f,1.0208f,0f,0f,-0.0574f,0f,-1.0192f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}