# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) {transformation: [-1.3303f,0f,0.0902f,0f,0f,1.3333f,0f,0f,-0.0902f,0f,-1.3303f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.3407f,0f,0.0909f,0f,0f,1.3438f,0f,0f,-0.0909f,0f,-1.3407f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nekutai) {transformation: [-0.9966f,0f,0.0819f,0f,0f,1f,0f,0f,-0.0819f,0f,-0.9966f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.9966f,0f,0.0819f,0f,0f,1f,0f,0f,-0.0819f,0f,-0.9966f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-0.9982f,-0.0497f,0.033f,0.3173f,-0.0496f,0.9988f,0.004f,1.3633f,-0.0331f,0.0024f,-0.9994f,0.0261f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-0.9991f,0.0401f,0.0117f,-0.3666f,0.0414f,0.9899f,0.1354f,1.3703f,-0.0061f,0.1357f,-0.9907f,-0.0301f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-0.9957f,0.0435f,0.0819f,-0.0102f,0.0436f,0.999f,0f,0f,-0.0819f,0.0036f,-0.9966f,0.0051f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-0.9957f,-0.0338f,0.0864f,0.0136f,-0.0436f,0.9925f,-0.1145f,-0.0118f,-0.0819f,-0.1178f,-0.9897f,0.0247f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cap) {transformation: [-1.4113f,0.0122f,0.0929f,0f,0f,1.4023f,-0.1846f,-0.0469f,-0.0937f,-0.1842f,-1.3992f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line) {transformation: [-1.1484f,0f,0.0944f,0f,0f,1.1523f,0f,0f,-0.0944f,0f,-1.1484f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(manto) {transformation: [-1.0174f,0f,0.0836f,0f,0f,1.0208f,0f,0f,-0.0836f,0f,-1.0174f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}