# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) {transformation: [-1.3321f,0f,-0.0579f,0f,0f,1.3333f,0f,0f,0.0579f,0f,-1.3321f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.3425f,0f,-0.0584f,0f,0f,1.3438f,0f,0f,0.0584f,0f,-1.3425f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nekutai) {transformation: [-0.8879f,0f,-0.46f,0f,0f,1f,0f,0f,0.46f,0f,-0.8879f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.8879f,0f,-0.46f,0f,0f,1f,0f,0f,0.46f,0f,-0.8879f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-0.8136f,0.0695f,-0.5773f,0.2698f,-0.13f,0.946f,0.2971f,1.3439f,0.5667f,0.3167f,-0.7606f,-0.1924f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-0.976f,-0.2142f,0.0387f,-0.2915f,-0.0225f,-0.0776f,-0.9967f,1.3439f,0.2165f,-0.9737f,0.0709f,0.151f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-0.9878f,0.0387f,-0.151f,-0.0014f,0.0413f,0.999f,-0.014f,0f,0.1503f,-0.0201f,-0.9884f,-0.0322f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-0.9819f,-0.1755f,0.0714f,0.0968f,-0.1876f,0.953f,-0.2377f,0.0156f,-0.0263f,-0.2468f,-0.9687f,-0.0501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cap) {transformation: [-1.4144f,0f,0f,0f,0f,1.4023f,-0.1846f,-0.0469f,0f,-0.1846f,-1.4023f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line) {transformation: [-1.0231f,0f,-0.5301f,0f,0f,1.1523f,0f,0f,0.5301f,0f,-1.0231f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(manto) {transformation: [-0.9064f,0f,-0.4696f,0f,0f,1.0208f,0f,0f,0.4696f,0f,-0.9064f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}