# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) {transformation: [-1.3321f,0f,-0.0563f,0f,0f,1.3333f,0f,0f,0.0563f,0f,-1.3321f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.3426f,0f,-0.0567f,0f,0f,1.3438f,0f,0f,0.0567f,0f,-1.3426f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nekutai) {transformation: [-0.894f,0f,-0.4481f,0f,0f,1f,0f,0f,0.4481f,0f,-0.894f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.894f,0f,-0.4481f,0f,0f,1f,0f,0f,0.4481f,0f,-0.894f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-0.8236f,0.0623f,-0.5638f,0.2726f,-0.1264f,0.9488f,0.2895f,1.3447f,0.5529f,0.3097f,-0.7735f,-0.1874f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-0.9774f,-0.2097f,0.028f,-0.2947f,-0.0219f,-0.0315f,-0.9993f,1.3447f,0.2105f,-0.9772f,0.0262f,0.1477f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-0.985f,0.039f,-0.168f,-0.0022f,0.0417f,0.999f,-0.0127f,0f,0.1674f,-0.0195f,-0.9857f,-0.0286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-0.9824f,-0.1734f,0.0689f,0.0951f,-0.1848f,0.9547f,-0.2333f,0.0151f,-0.0253f,-0.2419f,-0.97f,-0.0477f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cap) {transformation: [-1.4144f,0f,0f,0f,0f,1.4023f,-0.1846f,-0.0469f,0f,-0.1846f,-1.4023f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line) {transformation: [-1.0301f,0f,-0.5163f,0f,0f,1.1523f,0f,0f,0.5163f,0f,-1.0301f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(manto) {transformation: [-0.9126f,0f,-0.4574f,0f,0f,1.0208f,0f,0f,0.4574f,0f,-0.9126f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}