# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) {transformation: [-1.3323f,0f,-0.0519f,0f,0f,1.3333f,0f,0f,0.0519f,0f,-1.3323f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.3427f,0f,-0.0523f,0f,0f,1.3438f,0f,0f,0.0523f,0f,-1.3427f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nekutai) {transformation: [-0.9097f,0f,-0.4152f,0f,0f,1f,0f,0f,0.4152f,0f,-0.9097f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.9097f,0f,-0.4152f,0f,0f,1f,0f,0f,0.4152f,0f,-0.9097f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-0.8494f,0.0442f,-0.5258f,0.2796f,-0.1167f,0.9561f,0.2688f,1.3471f,0.5146f,0.2897f,-0.807f,-0.1736f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-0.9808f,-0.1952f,0.0016f,-0.3031f,-0.0203f,0.0937f,-0.9954f,1.3471f,0.1942f,-0.9763f,-0.0959f,0.1383f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-0.9849f,0.0397f,-0.1685f,-0.0027f,0.0422f,0.999f,-0.0112f,0f,0.1679f,-0.0181f,-0.9856f,-0.0242f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-0.984f,-0.1671f,0.0619f,0.0903f,-0.1768f,0.9592f,-0.2206f,0.0139f,-0.0225f,-0.228f,-0.9734f,-0.0412f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cap) {transformation: [-1.4144f,0f,0f,0f,0f,1.4023f,-0.1846f,-0.0469f,0f,-0.1846f,-1.4023f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line) {transformation: [-1.0483f,0f,-0.4784f,0f,0f,1.1523f,0f,0f,0.4784f,0f,-1.0483f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(manto) {transformation: [-0.9287f,0f,-0.4238f,0f,0f,1.0208f,0f,0f,0.4238f,0f,-0.9287f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}