# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) {transformation: [-1.3326f,0f,-0.0433f,0f,0f,1.3333f,0f,0f,0.0433f,0f,-1.3326f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.343f,0f,-0.0436f,0f,0f,1.3438f,0f,0f,0.0436f,0f,-1.343f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nekutai) {transformation: [-0.9369f,0f,-0.3496f,0f,0f,1f,0f,0f,0.3496f,0f,-0.9369f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.9369f,0f,-0.3496f,0f,0f,1f,0f,0f,0.3496f,0f,-0.9369f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-0.8944f,0.0148f,-0.4471f,0.2915f,-0.0976f,0.9689f,0.2274f,1.3518f,0.4366f,0.247f,-0.8651f,-0.146f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-0.9866f,-0.1587f,-0.038f,-0.3187f,-0.017f,0.3318f,-0.9432f,1.3518f,0.1623f,-0.9299f,-0.3301f,0.1189f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-0.9894f,0.0409f,-0.139f,-0.0032f,0.0426f,0.999f,-0.0094f,0f,0.1385f,-0.0152f,-0.9902f,-0.0196f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-0.9871f,-0.1526f,0.0486f,0.08f,-0.1591f,0.9681f,-0.1935f,0.0116f,-0.0175f,-0.1987f,-0.9799f,-0.0298f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cap) {transformation: [-1.4144f,0f,0f,0f,0f,1.4023f,-0.1846f,-0.0469f,0f,-0.1846f,-1.4023f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line) {transformation: [-1.0796f,0f,-0.4028f,0f,0f,1.1523f,0f,0f,0.4028f,0f,-1.0796f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(manto) {transformation: [-0.9564f,0f,-0.3568f,0f,0f,1.0208f,0f,0f,0.3568f,0f,-0.9564f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}