# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) {transformation: [-1.333f,0f,-0.0291f,0f,0f,1.3333f,0f,0f,0.0291f,0f,-1.333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.3434f,0f,-0.0293f,0f,0f,1.3438f,0f,0f,0.0293f,0f,-1.3434f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nekutai) {transformation: [-0.9713f,0f,-0.2377f,0f,0f,1f,0f,0f,0.2377f,0f,-0.9713f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.9713f,0f,-0.2377f,0f,0f,1f,0f,0f,0.2377f,0f,-0.9713f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-0.9518f,-0.015f,-0.3064f,0.3056f,-0.0658f,0.9856f,0.156f,1.3594f,0.2997f,0.1687f,-0.939f,-0.0989f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-0.9939f,-0.0884f,-0.0654f,-0.3415f,-0.0116f,0.6755f,-0.7372f,1.3594f,0.1094f,-0.732f,-0.6725f,0.0836f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-0.9969f,0.0424f,-0.0656f,-0.0037f,0.043f,0.999f,-0.0076f,0f,0.0652f,-0.0104f,-0.9978f,-0.0152f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-0.9921f,-0.1225f,0.0283f,0.0607f,-0.1252f,0.9821f,-0.1409f,0.0078f,-0.0105f,-0.1434f,-0.9896f,-0.0149f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cap) {transformation: [-1.4144f,0f,0f,0f,0f,1.4023f,-0.1846f,-0.0469f,0f,-0.1846f,-1.4023f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line) {transformation: [-1.1192f,0f,-0.2739f,0f,0f,1.1523f,0f,0f,0.2739f,0f,-1.1192f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(manto) {transformation: [-0.9916f,0f,-0.2426f,0f,0f,1.0208f,0f,0f,0.2426f,0f,-0.9916f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}