# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) {transformation: [-1.3333f,0f,-0.0149f,0f,0f,1.3333f,0f,0f,0.0149f,0f,-1.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.3437f,0f,-0.015f,0f,0f,1.3438f,0f,0f,0.015f,0f,-1.3437f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nekutai) {transformation: [-0.9925f,0f,-0.1226f,0f,0f,1f,0f,0f,0.1226f,0f,-0.9925f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.9925f,0f,-0.1226f,0f,0f,1f,0f,0f,0.1226f,0f,-0.9925f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-0.9873f,-0.0206f,-0.1577f,0.3126f,-0.0338f,0.9961f,0.0813f,1.367f,0.1554f,0.0856f,-0.9841f,-0.0507f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-0.9984f,-0.0285f,-0.0486f,-0.3603f,-0.006f,0.9111f,-0.4122f,1.367f,0.0561f,-0.4112f,-0.9098f,0.0445f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-0.999f,0.0433f,0.0083f,-0.0053f,0.0432f,0.999f,-0.0057f,0f,-0.0085f,-0.0053f,-0.9999f,-0.0112f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-0.9962f,-0.0862f,0.0116f,0.0393f,-0.0868f,0.9932f,-0.0779f,0.004f,-0.0048f,-0.0786f,-0.9969f,-0.0049f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cap) {transformation: [-1.4144f,0f,0f,0f,0f,1.4023f,-0.1846f,-0.0469f,0f,-0.1846f,-1.4023f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line) {transformation: [-1.1436f,0f,-0.1412f,0f,0f,1.1523f,0f,0f,0.1412f,0f,-1.1436f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(manto) {transformation: [-1.0131f,0f,-0.1251f,0f,0f,1.0208f,0f,0f,0.1251f,0f,-1.0131f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}