# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) {transformation: [-1.3333f,0f,-0.0063f,0f,0f,1.3333f,0f,0f,0.0063f,0f,-1.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.3437f,0f,-0.0063f,0f,0f,1.3438f,0f,0f,0.0063f,0f,-1.3437f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nekutai) {transformation: [-0.9987f,0f,-0.0518f,0f,0f,1f,0f,0f,0.0518f,0f,-0.9987f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.9987f,0f,-0.0518f,0f,0f,1f,0f,0f,0.0518f,0f,-0.9987f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-0.9977f,-0.0119f,-0.0663f,0.3135f,-0.0143f,0.9993f,0.0346f,1.3716f,0.0658f,0.0355f,-0.9972f,-0.0213f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-0.9997f,-0.0067f,-0.0228f,-0.3694f,-0.0025f,0.984f,-0.1784f,1.3716f,0.0237f,-0.1783f,-0.9837f,0.0192f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-0.9983f,0.0436f,0.0381f,-0.008f,0.0434f,0.999f,-0.0039f,0f,-0.0383f,-0.0023f,-0.9993f,-0.0077f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-0.9981f,-0.062f,0.0041f,0.0257f,-0.0621f,0.9975f,-0.0343f,0.0017f,-0.0019f,-0.0345f,-0.9994f,-0.0013f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cap) {transformation: [-1.4144f,0f,0f,0f,0f,1.4023f,-0.1846f,-0.0469f,0f,-0.1846f,-1.4023f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line) {transformation: [-1.1507f,0f,-0.0597f,0f,0f,1.1523f,0f,0f,0.0597f,0f,-1.1507f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(manto) {transformation: [-1.0195f,0f,-0.0529f,0f,0f,1.0208f,0f,0f,0.0529f,0f,-1.0195f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}