# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) {transformation: [-1.3333f,0f,-0.0019f,0f,0f,1.3333f,0f,0f,0.0019f,0f,-1.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.3437f,0f,-0.0019f,0f,0f,1.3438f,0f,0f,0.0019f,0f,-1.3437f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nekutai) {transformation: [-0.9999f,0f,-0.0154f,0f,0f,1f,0f,0f,0.0154f,0f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.9999f,0f,-0.0154f,0f,0f,1f,0f,0f,0.0154f,0f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-0.9998f,-0.004f,-0.0196f,0.3129f,-0.0042f,0.9999f,0.0103f,1.374f,0.0195f,0.0104f,-0.9998f,-0.0063f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-1f,-0.0011f,-0.007f,-0.3735f,-0.0007f,0.9986f,-0.0531f,1.374f,0.007f,-0.0531f,-0.9986f,0.0057f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-0.9983f,0.0436f,0.0376f,-0.0109f,0.0436f,0.999f,-0.0023f,0f,-0.0377f,-0.0007f,-0.9993f,-0.0046f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-0.9988f,-0.0491f,0.0011f,0.0186f,-0.0491f,0.9987f,-0.0104f,0.0005f,-0.0006f,-0.0104f,-0.9999f,-0.0003f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cap) {transformation: [-1.4144f,0f,0f,0f,0f,1.4023f,-0.1846f,-0.0469f,0f,-0.1846f,-1.4023f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line) {transformation: [-1.1521f,0f,-0.0177f,0f,0f,1.1523f,0f,0f,0.0177f,0f,-1.1521f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(manto) {transformation: [-1.0207f,0f,-0.0157f,0f,0f,1.0208f,0f,0f,0.0157f,0f,-1.0207f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}