# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) {transformation: [-1.3333f,0f,-0.0002f,0f,0f,1.3333f,0f,0f,0.0002f,0f,-1.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.3437f,0f,-0.0002f,0f,0f,1.3438f,0f,0f,0.0002f,0f,-1.3437f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nekutai) {transformation: [-1f,0f,-0.0019f,0f,0f,1f,0f,0f,0.0019f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1f,0f,-0.0019f,0f,0f,1f,0f,0f,0.0019f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-1f,-0.0005f,-0.0024f,0.3126f,-0.0005f,1f,0.0013f,1.3749f,0.0024f,0.0013f,-1f,-0.0008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-1f,-0.0001f,-0.0009f,-0.3748f,-0.0001f,1f,-0.0066f,1.3749f,0.0009f,-0.0066f,-1f,0.0007f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-0.9988f,0.0436f,0.0204f,-0.0136f,0.0436f,0.999f,-0.001f,0f,-0.0204f,-0.0001f,-0.9998f,-0.002f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-0.999f,-0.0443f,0.0001f,0.016f,-0.0443f,0.999f,-0.0013f,0.0001f,-0.0001f,-0.0013f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cap) {transformation: [-1.4144f,0f,0f,0f,0f,1.4023f,-0.1846f,-0.0469f,0f,-0.1846f,-1.4023f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line) {transformation: [-1.1523f,0f,-0.0022f,0f,0f,1.1523f,0f,0f,0.0022f,0f,-1.1523f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(manto) {transformation: [-1.0208f,0f,-0.002f,0f,0f,1.0208f,0f,0f,0.002f,0f,-1.0208f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}