# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) {transformation: [-1.328f,0f,0.1188f,0f,0f,1.3333f,0f,0f,-0.1188f,0f,-1.328f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.3384f,0f,0.1197f,0f,0f,1.3438f,0f,0f,-0.1197f,0f,-1.3384f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nekutai) {transformation: [-0.9941f,0f,0.1089f,0f,0f,1f,0f,0f,-0.1089f,0f,-0.9941f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.9941f,0f,0.1089f,0f,0f,1f,0f,0f,-0.1089f,0f,-0.9941f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-0.9969f,-0.0659f,0.0438f,0.3184f,-0.0658f,0.9978f,0.0043f,1.3594f,-0.0439f,0.0014f,-0.999f,0.0349f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-0.9985f,0.0525f,0.0179f,-0.3633f,0.0549f,0.982f,0.1808f,1.3687f,-0.0081f,0.1815f,-0.9834f,-0.0398f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-0.9931f,0.0434f,0.1089f,-0.0086f,0.0436f,0.999f,0f,0f,-0.1088f,0.0047f,-0.9941f,0.0069f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-0.9931f,-0.0263f,0.1142f,0.0121f,-0.0436f,0.9874f,-0.152f,-0.0156f,-0.1088f,-0.1559f,-0.9818f,0.0328f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cap) {transformation: [-1.409f,0.0161f,0.1222f,0f,0f,1.4023f,-0.1846f,-0.0469f,-0.1232f,-0.1839f,-1.397f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line) {transformation: [-1.1454f,0f,0.1254f,0f,0f,1.1523f,0f,0f,-0.1254f,0f,-1.1454f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(manto) {transformation: [-1.0148f,0f,0.1111f,0f,0f,1.0208f,0f,0f,-0.1111f,0f,-1.0148f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}