# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) {transformation: [-1.3251f,0f,0.1478f,0f,0f,1.3333f,0f,0f,-0.1478f,0f,-1.3251f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.3355f,0f,0.149f,0f,0f,1.3438f,0f,0f,-0.149f,0f,-1.3355f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nekutai) {transformation: [-0.9907f,0f,0.1357f,0f,0f,1f,0f,0f,-0.1357f,0f,-0.9907f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.9907f,0f,0.1357f,0f,0f,1f,0f,0f,-0.1357f,0f,-0.9907f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-0.9951f,-0.0821f,0.0545f,0.3193f,-0.082f,0.9966f,0.004f,1.3555f,-0.0547f,-0.0005f,-0.9985f,0.0437f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-0.9976f,0.0642f,0.0253f,-0.3595f,0.0683f,0.9716f,0.2264f,1.3669f,-0.01f,0.2276f,-0.9737f,-0.0493f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-0.9898f,0.0432f,0.1357f,-0.0071f,0.0436f,0.999f,0f,0f,-0.1356f,0.0059f,-0.9907f,0.0089f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-0.9898f,-0.0167f,0.1414f,0.0102f,-0.0436f,0.981f,-0.1893f,-0.0195f,-0.1356f,-0.1935f,-0.9717f,0.0408f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cap) {transformation: [-1.4061f,0.02f,0.152f,0f,0f,1.4023f,-0.1846f,-0.0469f,-0.1533f,-0.1835f,-1.394f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line) {transformation: [-1.1416f,0f,0.1564f,0f,0f,1.1523f,0f,0f,-0.1564f,0f,-1.1416f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(manto) {transformation: [-1.0114f,0f,0.1385f,0f,0f,1.0208f,0f,0f,-0.1385f,0f,-1.0114f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}