# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) {transformation: [-1.3216f,0f,0.1764f,0f,0f,1.3333f,0f,0f,-0.1764f,0f,-1.3216f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.3319f,0f,0.1778f,0f,0f,1.3438f,0f,0f,-0.1778f,0f,-1.3319f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nekutai) {transformation: [-0.9869f,0f,0.1612f,0f,0f,1f,0f,0f,-0.1612f,0f,-0.9869f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.9869f,0f,0.1612f,0f,0f,1f,0f,0f,-0.1612f,0f,-0.9869f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-0.9931f,-0.0974f,0.0648f,0.3199f,-0.0973f,0.9952f,0.0033f,1.3518f,-0.0648f,-0.003f,-0.9979f,0.0522f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-0.9967f,0.0747f,0.0332f,-0.3555f,0.0809f,0.9595f,0.2699f,1.3651f,-0.0117f,0.2717f,-0.9623f,-0.0581f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-0.986f,0.043f,0.1612f,-0.0058f,0.0436f,0.999f,0f,0f,-0.161f,0.007f,-0.9869f,0.0108f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-0.986f,-0.0057f,0.1667f,0.0079f,-0.0436f,0.9735f,-0.2245f,-0.0232f,-0.161f,-0.2286f,-0.9601f,0.0483f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cap) {transformation: [-1.4025f,0.0239f,0.1815f,0f,0f,1.4023f,-0.1846f,-0.0469f,-0.183f,-0.1831f,-1.3905f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line) {transformation: [-1.1372f,0f,0.1857f,0f,0f,1.1523f,0f,0f,-0.1857f,0f,-1.1372f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(manto) {transformation: [-1.0075f,0f,0.1645f,0f,0f,1.0208f,0f,0f,-0.1645f,0f,-1.0075f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}