# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) {transformation: [-1.3177f,0f,0.2035f,0f,0f,1.3333f,0f,0f,-0.2035f,0f,-1.3177f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.328f,0f,0.2051f,0f,0f,1.3438f,0f,0f,-0.2051f,0f,-1.328f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nekutai) {transformation: [-0.9829f,0f,0.184f,0f,0f,1f,0f,0f,-0.184f,0f,-0.9829f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.9829f,0f,0.184f,0f,0f,1f,0f,0f,-0.184f,0f,-0.9829f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-0.9911f,-0.1109f,0.074f,0.3202f,-0.111f,0.9938f,0.0022f,1.3485f,-0.0737f,-0.006f,-0.9973f,0.0599f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-0.9957f,0.0834f,0.0412f,-0.3513f,0.0921f,0.9466f,0.3088f,1.3633f,-0.0132f,0.3113f,-0.9502f,-0.0657f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-0.982f,0.0429f,0.184f,-0.0048f,0.0436f,0.999f,0f,0f,-0.1838f,0.008f,-0.9829f,0.0126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-0.982f,0.0057f,0.1888f,0.0056f,-0.0436f,0.9657f,-0.2559f,-0.0265f,-0.1838f,-0.2595f,-0.9481f,0.055f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cap) {transformation: [-1.3985f,0.0276f,0.2096f,0f,0f,1.4023f,-0.1846f,-0.0469f,-0.2114f,-0.1825f,-1.3865f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line) {transformation: [-1.1326f,0f,0.212f,0f,0f,1.1523f,0f,0f,-0.212f,0f,-1.1326f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(manto) {transformation: [-1.0034f,0f,0.1878f,0f,0f,1.0208f,0f,0f,-0.1878f,0f,-1.0034f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}