# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair) {transformation: [-1.3137f,0f,0.2282f,0f,0f,1.3333f,0f,0f,-0.2282f,0f,-1.3137f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.3239f,0f,0.23f,0f,0f,1.3438f,0f,0f,-0.23f,0f,-1.3239f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(nekutai) {transformation: [-0.9792f,0f,0.2028f,0f,0f,1f,0f,0f,-0.2028f,0f,-0.9792f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.9792f,0f,0.2028f,0f,0f,1f,0f,0f,-0.2028f,0f,-0.9792f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-0.9892f,-0.122f,0.0816f,0.3203f,-0.1223f,0.9925f,0.001f,1.3458f,-0.0811f,-0.009f,-0.9967f,0.0663f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [-0.9948f,0.0902f,0.0483f,-0.3471f,0.1013f,0.9346f,0.341f,1.3613f,-0.0144f,0.3442f,-0.9388f,-0.0719f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [-0.9783f,0.0427f,0.2028f,-0.0039f,0.0436f,0.999f,0f,0f,-0.2026f,0.0088f,-0.9792f,0.0141f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [-0.9783f,0.0162f,0.2066f,0.0034f,-0.0436f,0.9585f,-0.2817f,-0.0292f,-0.2026f,-0.2846f,-0.937f,0.0605f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(cap) {transformation: [-1.3943f,0.031f,0.2356f,0f,0f,1.4023f,-0.1846f,-0.0469f,-0.2376f,-0.182f,-1.3824f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(line) {transformation: [-1.1283f,0f,0.2337f,0f,0f,1.1523f,0f,0f,-0.2337f,0f,-1.1283f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(manto) {transformation: [-0.9996f,0f,0.207f,0f,0f,1.0208f,0f,0f,-0.207f,0f,-0.9996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}