# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.skyglim.kalmia.animation.stand.playing
tag @s remove aj.skyglim.kalmia.animation.hover.playing
tag @s remove aj.skyglim.kalmia.animation.hi.playing
tag @s remove aj.skyglim.kalmia.animation.hover_stay.playing