# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(ahoge) { transformation: [1.4594f,0f,0f,0f,0f,1.4594f,0f,0f,0f,0f,1.4594f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(head) { transformation: [1.3438f,0f,0f,0f,0f,1.3438f,0f,0f,0f,0f,1.3438f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(body) { transformation: [1.0042f,0f,0f,0f,0f,1.0042f,0f,0f,0f,0f,1.0042f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(right1) { transformation: [1f,0f,0f,-0.3125f,0f,1f,0f,1.3125f,0f,0f,1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(left1) { transformation: [1f,0f,0f,0.3125f,0f,1f,0f,1.375f,0f,0f,1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(left) { transformation: [1f,0f,0f,0.25f,0f,1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(right) { transformation: [1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,1f], start_interpolation: 0 }