# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "aj:skyglim/avelian"
data modify storage animated_java:temp entry.data.rig_hash set value "31c7a3fa3871b2ba9e80cd2c2834b234b0773325a1da43cf1d9166e7a1634848"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=aj.skyglim.avelian.node.hair] run function aj:skyglim/avelian/zzz/summon/as_node/hair
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.hair set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.skyglim.avelian.node.head] run function aj:skyglim/avelian/zzz/summon/as_node/head
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.head set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.skyglim.avelian.node.nekutai] run function aj:skyglim/avelian/zzz/summon/as_node/nekutai
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.nekutai set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.skyglim.avelian.node.body] run function aj:skyglim/avelian/zzz/summon/as_node/body
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.body set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.skyglim.avelian.node.right1] run function aj:skyglim/avelian/zzz/summon/as_node/right1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.skyglim.avelian.node.left1] run function aj:skyglim/avelian/zzz/summon/as_node/left1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.skyglim.avelian.node.left] run function aj:skyglim/avelian/zzz/summon/as_node/left
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.skyglim.avelian.node.right] run function aj:skyglim/avelian/zzz/summon/as_node/right
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.skyglim.avelian.node.cap] run function aj:skyglim/avelian/zzz/summon/as_node/cap
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.cap set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.skyglim.avelian.node.line] run function aj:skyglim/avelian/zzz/summon/as_node/line
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.line set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.skyglim.avelian.node.manto] run function aj:skyglim/avelian/zzz/summon/as_node/manto
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.manto set from storage animated_java:gu out
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:skyglim/avelian/zzz/set_default_pose
execute if data storage animated_java:temp args.variant run function aj:skyglim/avelian/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function aj:skyglim/avelian/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new