# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:skyglim/cecile rig_hash set value '3d453d7e350341159bbf61bfff223dc3eebe014198de9866f2323e48cbae622c'
scoreboard objectives add aj.stand.frame dummy
scoreboard objectives add aj.point.frame dummy