# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.skyglim.avelian.animation.sit.playing] run function aj:skyglim/avelian/animations/sit/zzz/on_tick
execute if entity @s[tag=aj.skyglim.avelian.animation.stand.playing] run function aj:skyglim/avelian/animations/stand/zzz/on_tick
execute if entity @s[tag=aj.skyglim.avelian.animation.punch.playing] run function aj:skyglim/avelian/animations/punch/zzz/on_tick
execute on passengers run rotate @s ~ ~