# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.skyglim.kalmia.animation.stand.playing] run function aj:skyglim/kalmia/animations/stand/zzz/on_tick
execute if entity @s[tag=aj.skyglim.kalmia.animation.hover.playing] run function aj:skyglim/kalmia/animations/hover/zzz/on_tick
execute if entity @s[tag=aj.skyglim.kalmia.animation.hi.playing] run function aj:skyglim/kalmia/animations/hi/zzz/on_tick
execute if entity @s[tag=aj.skyglim.kalmia.animation.hover_stay.playing] run function aj:skyglim/kalmia/animations/hover_stay/zzz/on_tick
execute on passengers run rotate @s ~ ~