# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:skyglim/avelian rig_hash set value '31c7a3fa3871b2ba9e80cd2c2834b234b0773325a1da43cf1d9166e7a1634848'
scoreboard objectives add aj.sit.frame dummy
scoreboard objectives add aj.stand.frame dummy
scoreboard objectives add aj.punch.frame dummy