# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set @s aj.punch.frame 0
tag @s add aj.transforms_only
execute at @s run function aj:skyglim/avelian/animations/punch/zzz/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only
tag @s remove aj.skyglim.avelian.animation.punch.playing