# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) {transformation: [1.3438f,0f,0f,0f,0f,1.3438f,0f,0f,0f,0f,1.3438f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(wear) {transformation: [1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [1.0021f,0f,0f,0f,0f,1.0021f,0f,0f,0f,0f,1.0021f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right1) {transformation: [-0.8192f,0.5736f,0f,-0.3594f,-0.5736f,-0.8192f,0f,1.4844f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left1) {transformation: [0.9763f,-0.2164f,0f,0.3594f,0.2164f,0.9763f,0f,1.25f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left) {transformation: [0.9962f,-0.0872f,0f,0.2969f,0.0872f,0.9962f,0f,0f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right) {transformation: [0.9962f,0.0872f,0f,-0.0469f,-0.0872f,0.9962f,0f,0f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(skirt) {transformation: [1f,0f,0f,0f,0f,1f,0f,0.125f,0f,0f,1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}