# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "aj:skyglim/cecile"
data modify storage animated_java:temp entry.data.rig_hash set value "3d453d7e350341159bbf61bfff223dc3eebe014198de9866f2323e48cbae622c"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=aj.skyglim.cecile.node.ahoge] run function aj:skyglim/cecile/zzz/summon/as_node/ahoge
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ahoge set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.skyglim.cecile.node.head] run function aj:skyglim/cecile/zzz/summon/as_node/head
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.head set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.skyglim.cecile.node.body] run function aj:skyglim/cecile/zzz/summon/as_node/body
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.body set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.skyglim.cecile.node.right1] run function aj:skyglim/cecile/zzz/summon/as_node/right1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.skyglim.cecile.node.left1] run function aj:skyglim/cecile/zzz/summon/as_node/left1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.skyglim.cecile.node.left] run function aj:skyglim/cecile/zzz/summon/as_node/left
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.skyglim.cecile.node.right] run function aj:skyglim/cecile/zzz/summon/as_node/right
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right set from storage animated_java:gu out
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:skyglim/cecile/zzz/set_default_pose
execute if data storage animated_java:temp args.variant run function aj:skyglim/cecile/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function aj:skyglim/cecile/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new