# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:skyglim/kalmia rig_hash set value 'd301018d6674768317c62ebd0e32331b672cb4a93d9ad306536aca7f966fba69'
scoreboard objectives add aj.stand.frame dummy
scoreboard objectives add aj.hover.frame dummy
scoreboard objectives add aj.hi.frame dummy
scoreboard objectives add aj.hover_stay.frame dummy