# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.stand.frame
scoreboard objectives remove aj.hover.frame
scoreboard objectives remove aj.hi.frame
scoreboard objectives remove aj.hover_stay.frame
tellraw @a [[{color:gray,text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:dark_gray,italic:true,text:'\n (aj:skyglim/kalmia)'},'\n → '],[{text:'Successfully uninstalled ',color:green},{text:'aj:skyglim/kalmia',color:yellow},{text:'!'},{text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.',color:gray,italic:true}],'\n']