# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.skyglim.cecile.animation.stand.playing] run function aj:skyglim/cecile/animations/stand/zzz/on_tick
execute if entity @s[tag=aj.skyglim.cecile.animation.point.playing] run function aj:skyglim/cecile/animations/point/zzz/on_tick
execute on passengers run rotate @s ~ ~