# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) { transformation: [1.3438f,0f,0f,0f,0f,1.3438f,0f,0f,0f,0f,1.3438f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(wear) { transformation: [1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(body) { transformation: [1.0021f,0f,0f,0f,0f,1.0021f,0f,0f,0f,0f,1.0021f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(right1) { transformation: [1f,0f,0f,-0.3437f,0f,1f,0f,1.375f,0f,0f,1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(left1) { transformation: [1f,0f,0f,0.3438f,0f,1f,0f,1.25f,0f,0f,1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(left) { transformation: [1f,0f,0f,0.25f,0f,1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(right) { transformation: [1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(skirt) { transformation: [1f,0f,0f,0f,0f,1f,0f,0.125f,0f,0f,1f,0f,0f,0f,0f,1f], start_interpolation: -1 }